biblio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from contact.views import MessageAddView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shelf/', include('shelf.urls', namespace='shelf')),
    url(r'^contact/$', MessageAddView.as_view()),
]

shelf/urls.py
from django.conf.urls import include, url
from views import AuthorDetailView
from views import AuthorListView

urlpatterns = [
    url(r'^authors/$', AuthorListView.as_view(), name='author-list'),
    url(r'^authors/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
]

contact/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return "message from {0}".format(self.name)

shelf/models.py
# coding: utf-8
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)


class Publisher(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    isbn = models.CharField(max_length=17)
    publisher = models.ForeignKey(Publisher)

    def __str__(self):
        return self.title

contact/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'message')

contact/views.py
from django.views.generic import DetailView, FormView
from .models import Message
from .forms import MessageForm

class MessageDetailView(DetailView):
    model = Message

class MessageAddView(FormView):
    form_class = MessageForm
    template_name = 'contact/message_form.html'

shelf/views.py
# coding: utf-8
from __future__ import unicode_literals
from __future__ import absolute_import

from django.views.generic import ListView, DetailView
from django.shortcuts import render
from .models import Author

class AuthorListView(ListView):
    model = Author

class AuthorDetailView(DetailView):
    model = Author

contact/templates/contact/message_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block 'content' %}
<div><a href="{% url 'shelf:author-list' %}">Powrót do listy</a></div>
{{ object.last_name }}, {{ object.first_name }}
{% endblock %}

shelf/templates/shelf/author_list.html
{% extends "base.html" %}

{% block 'content' %}
Moja treść
<ul>
{% for author in object_list %}
    <li><a href="{% url 'shelf:author-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a></li>
{%endfor%}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    {% block 'content' %}
    {% endblock %}
</body>
</html>